### ISSUE TITLE
NullPointerException when trying to generate doc with mvn compile

### ISSUE THREAD

**Issue by itbh-chandl** [dgreen99/swagger-jaxrs-maven#3]
I encountered the stated problem with my swagger implementation.

added the entry in the dependencies section at my top-level pom.xml
```
<!-- Add a Swagger annotations dependency so that Swagger annotations ca be used within the project -->
      <dependency>
	<groupId>io.swagger</groupId>
	<artifactId>swagger-annotations</artifactId>
	<version>1.5.3</version>
      </dependency>
```
and for each package within the plugin section of the pom.xml
```
<plugin>
     <groupId>com.greensopinion.swagger</groupId>
     <artifactId>jaxrs-gen</artifactId>
     <version>1.3.0</version>
     <configuration>
          <apiVersion>1.0</apiVersion>
          <apiBasePath>/api/latest</apiBasePath>
          <packageNames>
                 <param>at.itbh.kabelplus.maus.admin</param>
          </packageNames>
          <outputFolder>${project.build.directory}/web/api/docs</outputFolder>
     </configuration>
     <executions>
         <execution>
              <goals>
                    <goal>generate</goal>
              </goals>
         </execution>
     </executions>
</plugin>
```
when I call mvn compile the following error occurs
```
Failed to execute goal com.greensopinion.swagger:jaxrs-gen:1.3.0:generate (default) on project jobs: Execution default of goal com.greensopinion.swagger:jaxrs-gen:1.3.0:generate failed. NullPointerException
```
with the stack trace:
```
Caused by: java.lang.NullPointerException
at com.greensopinion.swagger.jaxrsgen.model.GsonIntrospector.modelFields(GsonIntrospector.java:81)
at com.greensopinion.swagger.jaxrsgen.model.GsonIntrospector.fieldModelClasses(GsonIntrospector.java:45)
at com.greensopinion.swagger.jaxrsgen.model.GsonIntrospector.fieldModelClasses(GsonIntrospector.java:49)
at com.greensopinion.swagger.jaxrsgen.model.GsonIntrospector.fieldModelClasses(GsonIntrospector.java:40)
at com.greensopinion.swagger.jaxrsgen.model.ServiceBuilder.methods(ServiceBuilder.java:109)
at com.greensopinion.swagger.jaxrsgen.model.ApiBuilder.service(ApiBuilder.java:50)
at com.greensopinion.swagger.jaxrsgen.SwaggerJaxrsGeneratorMojo.execute(SwaggerJaxrsGeneratorMojo.java:110)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
... 21 more
```

Do you have an idea what causes that NullPointerException?
thanks a lot for your help!

**Comment by greensopinion** [comment]
Thanks for the detailed issue and apologies that it's been so long without a response!

Any chance one of your model classes is an interface?  If so, try switching it to a Java class instead, that should do the trick.

**Comment by abstratt** [comment]
@greensopinion Just hit the same issue. :) We have 133 endpoints specified across 48 interfaces. Luckily, all endpoints returned "Response" so it was easy to do a mass conversion to abstract Java classes. Hopefully that will do the trick.
