### ISSUE TITLE
NPE dealing with arrays in query parameters

### ISSUE THREAD

**Issue by abstratt** [dgreen99/swagger-jaxrs-maven#4]
Saw NPEs in two places (spotted the second after "fixing" the first occurrence).

```
Caused by: java.lang.NullPointerException
	at com.greensopinion.swagger.jaxrsgen.model.ApiTypes.calculateTypeName(ApiTypes.java:94)
	at com.greensopinion.swagger.jaxrsgen.model.ServiceOperationBuilder.addParameter(ServiceOperationBuilder.java:119)
	at com.greensopinion.swagger.jaxrsgen.model.ServiceOperationBuilder.method(ServiceOperationBuilder.java:81)
	at com.greensopinion.swagger.jaxrsgen.model.ServiceBuilder.methods(ServiceBuilder.java:91)
	at com.greensopinion.swagger.jaxrsgen.model.ApiBuilder.service(ApiBuilder.java:50)
	at com.greensopinion.swagger.jaxrsgen.SwaggerJaxrsGeneratorMojo.execute(SwaggerJaxrsGeneratorMojo.java:106)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
```

In this code:

```
		String typeName = typeNameByClass.get(parameterType);

		if (typeName != null) {
			return typeName;
		}

		if (parameterType.isPrimitive() || parameterType.getPackage().getName().equals("java.lang")) {
```

a NPE will occur at the last line if parameterType is a primitive array.

Same happens in "isModelClass" in the same class:

```
		return !clazz.isPrimitive() && !clazz.getPackage().getName().startsWith("java.")
				&& !clazz.getPackage().getName().startsWith("javax.")
				&& !clazz.getPackage().getName().startsWith("com.sun.jersey.multipart");

```

For an array (even if of primitives), #isPrimitive() will return false, and getPackage() will return null.

**Comment by greensopinion** [comment]
Agreed, arrays are something that is not yet supported.  A workaround might be to use a list instead.

Considering issuing a pull-request to add support for arrays.
